name: Tests

on: [ push, pull_request ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run test:typings

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        electron-version:
          - 5.0.13
          - 6.1.12
          - 7.3.3
          - 8.5.5
          - 9.4.4
          - 10.4.7
          - 11.5.0
          - 12.2.3
          - 13.6.9
          - 14.2.9
          - 15.5.7
          - 16.2.8
          - 17.4.11
          - 18.3.15
          - 19.1.9
          - 20.3.12
          - 21.4.4
          - 22.3.27
          - 23.3.13
          - 24.8.8
          - 25.9.8
          - 26.6.10
          - 27.3.11
          - 28.3.3
          - 29.4.5
          - 30.2.0
          - 31.2.1
        formdata-version:
          - 4.0.0
        include:
          - electron-version: 31.2.1
            formdata-version: 1.0.0
          - electron-version: 31.2.1
            formdata-version: 2.5.1
          - electron-version: 31.2.1
            formdata-version: 3.0.1
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: if [ "${{ matrix.electron-version }}" ]; then npm install electron@^${{ matrix.electron-version }}; fi
      - run: if [ "${{ matrix.formdata-version }}" ]; then npm install form-data@^${{ matrix.formdata-version }}; fi
      - run: npm run report
