name: Tests

on: [ push, pull_request ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run test:typings

  tests:
    runs-on: ubuntu-latest
    # strategy:
      # matrix:
        # electron-version: [ 5.0.13, 6.1.12, 7.3.3, 8.5.5, 9.4.4, 10.4.7, 11.5.0, 12.2.2, 13.6.0, 14.2.0, 15.3.0 ]
        # formdata-version: [ 1.0.0, 2.5.1, 3.0.1, 4.0.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      # - run: npm install electron@^${{ matrix.electron-version }}
      # - run: npm install form-data@^${{ matrix.formdata-version }}
      - run: dig this-is-an-invalid-domain.com
      - run: dig this-is-an-invalid-domain.com @8.8.8.8
      - run: npm run report
