name: Tests

on: [ push, pull_request ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run test:typings

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        electron-version: [ 5.0.13, 6.1.12, 7.3.3, 8.5.5, 9.4.4, 10.4.7, 11.5.0, 12.2.2, 13.6.0, 14.2.0, 15.3.0 ]
        include:
          - electron-version: 15.3.0
            formdata-version: 1.0.0
          - electron-version: 15.3.0
            formdata-version: 2.5.1
          - electron-version: 15.3.0
            formdata-version: 3.0.1
          - electron-version: 15.3.0
            formdata-version: 4.0.0
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: if [ "${{ matrix.electron-version }}" ]; then npm install electron@^${{ matrix.electron-version }}; fi
      - run: if [ "${{ matrix.formdata-version }}" ]; then npm install form-data@^${{ matrix.formdata-version }}; fi
      - run: npm run report
